export const airlineCodeMap: Record<string, string> = {
    "AA": "American Airlines",
    "AC": "Air Canada",
    "AF": "Air France",
    "AI": "Air India",
    "AS": "Alaska Airlines",
    "AY": "Finnair",
    "AZ": "ITA Airways",
    "BA": "British Airways",
    "B6": "JetBlue Airways",
    "BR": "EVA Air",
    "CI": "China Airlines",
    "CX": "Cathay Pacific",
    "CZ": "China Southern Airlines",
    "DL": "Delta Air Lines",
    "EK": "Emirates",
    "ET": "Ethiopian Airlines",
    "EY": "Etihad Airways",
    "F9": "Frontier Airlines",
    "FI": "Icelandair",
    "IB": "Iberia",
    "JL": "Japan Airlines",
    "KE": "Korean Air",
    "KL": "KLM Royal Dutch Airlines",
    "LH": "Lufthansa",
    "LX": "Swiss International Air Lines",
    "LY": "El Al Israel Airlines",
    "MS": "EgyptAir",
    "MU": "China Eastern Airlines",
    "NH": "All Nippon Airways",
    "NK": "Spirit Airlines",
    "NZ": "Air New Zealand",
    "OS": "Austrian Airlines",
    "OZ": "Asiana Airlines",
    "QF": "Qantas",
    "QR": "Qatar Airways",
    "RJ": "Royal Jordanian",
    "SA": "South African Airways",
    "SK": "SAS Scandinavian Airlines",
    "SQ": "Singapore Airlines",
    "SU": "Aeroflot",
    "SV": "Saudia",
    "TG": "Thai Airways",
    "TK": "Turkish Airlines",
    "TP": "TAP Air Portugal",
    "UA": "United Airlines",
    "VS": "Virgin Atlantic",
    "WN": "Southwest Airlines",
    "WS": "WestJet",
    "WY": "Oman Air",
    "6X": "British Airways", // Mapped from Amadeus Test for demo purposes
    "AT": "Royal Air Maroc",
    "AD": "Azul",
    "AV": "Avianca",
    "CM": "Copa Airlines",
    "JJ": "LATAM Airlines",
    "LA": "LATAM Airlines",
    "LP": "LATAM Airlines",
    "XL": "LATAM Airlines",
    "4M": "LATAM Airlines",
    // Add more as needed
};
